---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myapp-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgDVuKAxNklpMuVDvYI6H/m1X2EyfKceQVINH4F2X61QjAwps7ytNnFn4voDeAlr/bYauKuxONTW5HncFlrf/KuU39kK8h+Xr0s9G4kx3imTS2/3MRik8p67qSE9BcBArp5orZLtWZF1IzNls/vPFH8jhTB0/UPz8CG2fQtwtlkLYwQc6OJi2N5K0s6iGha5r5FPYs2SOB6qctUSYi0TuoCq7GOg/JOCbb00BgH6yCr/786jqY9SW5GZwmA2JOI2KLwDJrlMxXZQMGLPfZFiJ1YY1/fN9u8+/7Xqj7xP8Zk2GQnpua53jQZi3FHD+U6TrbPsrKzkRURaVuOkuJYuSESheFxG/f9xGIbuJF91hTPzws25Ze/eAoWPwAgqqkmDkiSQ7FOOBzESwbYqOritjRssTuSLyqGsMBYfBzXVGXbhX8HIuSEumUCO5dSz9tozk8Vh2iQyWyYz1gWiUAN2LK3UtzcsYaUOqOQzgIGeCv+SaLdnSt10m7KI58qc5bLCf2wZ6kzGNpUD2W9pn045vIS6dytroQRf+iN5ISXDxHoTa5g1a+itm081Q3mkEewm0o20fvUXwqNdikl4ux3nQSZqS9EZCpah6/LS9MIQmUeGkgm41j2dsZ64U2fF3QN8k3MY+cQQ4TEJuubb6UPypidCo1x1Xv4mqlMF6WYshAMFv8QUcGy8uFuLpk0HWE+oH5xh6YpuN+JwVQ==
    DB_USERNAME: AgDABvuApwzZfzrKzHxmS0iOjaxxF/3e0h8QV79W7FuRZVdzSGBOrg7j7X1wVVmyekrYWGpOr3od1HFHA3cCgwbbj9osBO4OZmGcKTiac+PauhVm7E+5dpNTZtTBqPtTbOADEqUjpiIIuqF1A9zXBkkuOPlLFaWbROHc7IFFB0ivSL36j/xJpeZ07sr4/wLzJKcnumuZZMYOSW/LGOEO3iAPul4Gb5/xpLIV2/sw45wfxh4S09EZ+wSV4fMY2zkbymgc5HVmTDUEq2rqV5vpRuq44vN+V15tqA0P5UALImIjxco9O0A8cK1ZvAmfv5BkKD2toVqkKZh4S4tUvnUtn0kZFteif1NiyLxgPOLUZPaWvPH5QS9Q9G6hawpzGiikH+c841VDmvUaZ5d4uTOKrjbcpTtuC3AkiZvlb/oP6cMgsRO5zffWyHs52CX5SWAQ4+8xgcLHC554jcd+LDGk7/hVQCdlHdyuNpzv7Yja4b3CYsfc2CFT7Y03x8jGa0iM5vyVnaiLJBg+5+z+8zbD1Ksor/+fxaa4CuHrAJyctCiFxp2nOOFmkKW0ULbbVepBQIFjftVtllSupttUcRgSWD8lbPZCtEKZOF5v88qZP79cqRLX2lrCvxu9WGczERcfzo3U3wY+ttY6LjP+qlK/ZkE+SDYWFXBLKnHsjaYQ/RxBwdrRSzywsXNHN0u+5m5QNa2OFdmaI5S0mw==
  template:
    metadata:
      creationTimestamp: null
      name: myapp-secret
      namespace: default
    type: Opaque
