name: Deploy to Kubernetes with Sealed Secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Deploy Sealed Secret
        run: kubectl apply -f sealed-secret.yaml

      - name: Deploy Application
        run: kubectl apply -f deployment.yaml
